#!/bin/sh

VERSION="12.3"

if [ ! -d "snapraid-${VERSION}" ]; then
  wget https://github.com/amadvance/snapraid/releases/download/v${VERSION}/snapraid-${VERSION}.tar.gz
  tar xzf snapraid-${VERSION}.tar.gz
  /bin/rm -f snapraid-${VERSION}.tar.gz
fi

cd snapraid-${VERSION}
rm -rf debian
cp -rf ../debian ./
debuild -i -us -uc -b
