#!/bin/sh

VERSION="10.0"

if [ ! -d "snapraid-${VERSION}" ]; then
  wget https://github.com/amadvance/snapraid/archive/v${VERSION}.tar.gz -O snapraid-${VERSION}.tar.gz
  tar xzf snapraid-${VERSION}.tar.gz
  /bin/rm -f snapraid-${VERSION}.tar.gz
fi

cd snapraid-${VERSION}
rm -rf debian
cp -rf ../debian ./
debuild -i -us -uc -b
